services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: streamix
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025" # Mailpit web UI
      - "1025:1025" # SMTP server
    restart: unless-stopped

volumes:
  db:
